# 개발환경과 서비스 환경 분리
spring:
  profiles:
    active: dev
    group:
      "blue": "blue, secret, database"
      "green": "green, secret, database"
  #    include: secret, database

  devtools:
    livereload:
      enabled: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mvc:
    # /static/ 으로 시작하는 요청에 대해 정적 파일 서빙
    static-path-pattern: /static/**

  web:
    resources:
      # 정적 파일 탐색 장소
      static-locations: file:uploads/, classpath:/static

---
spring:
  config:
    activate:
      on-profile: blue

server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: green

server:
  port: 8082

---
# Swagger
# Springdoc OpenAPI 설정
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html


---
# AWS S3 설정
cloud:
  aws:
    s3:
      bucket: hiddenpiece
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    credentials:
      access-key: AKIAZ4ENSFLQJHQJH3XV
      secret-key: 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