# 나중에 yaml 파일 개발 환경에 따라 분리 가능성 있음
spring:
  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mvc:
    # /static/ 으로 시작하는 요청에 대해 정적 파일 서빙
    static-path-pattern: /static/**

  web:
    resources:
      # 정적 파일 탐색 장소
      static-locations: file:profile/, classpath:/static

  data:
    redis:
      host: 13.125.230.133
      port: 6379

  security:
    oauth2:
      client:
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          naver:
            client-id: bC4UMAGbSVxozYfaO9D7
            client-secret: FRY3k8PDhA
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            client-name: Naver
            scope:
              - name
              - email
              - profile_img
          kakao:
            client-id: 9b5d206b8dc434b63c8314c83ef1ca2b
            client-secret: GZoEK4KDIy3ugqypcOAYyfH6H8WvSXcM
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
              - profile_image
          google:
            client-id: 642961280337-n5sr4uc6q8q6a6u2vo4oe3e8qnolj5ig.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - profile
              - email

jwt:
  secret: aaaabbbsdifqbvaesoioegwaaaabbbsdifqbvaesoioegwaaaabbbsdifqbvaesasdfqve
  access-token-expiration-millis: 3600000
  refresh-token-expiration-millis: 21600000
