# 개발환경과 서비스 환경 분리
spring:
  profiles:
    include: secret, database

  devtools:
    livereload:
      enabled: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mvc:
    # /static/ 으로 시작하는 요청에 대해 정적 파일 서빙
    static-path-pattern: /static/**

  web:
    resources:
      # 정적 파일 탐색 장소
      static-locations: file:profile/, classpath:/static

---
spring:
  config:
    activate:
      on-profile: blue

server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: green

server:
  port: 8082