spring:
  data:
    redis:
      port: 6379

  datasource:
    url: jdbc:mysql://database-hidden-piece.cywe1k6qhv3v.ap-northeast-2.rds.amazonaws.com:3306/demo # 수정 필요
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root # 수정 필요
    password: password # 수정 필요

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
