version: '3'

services:
  web_blue:
    container_name: web_blue
    image: zerobird/hidden-piece
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=blue
    ports:
      - '8081:8081'
    networks:
      - app_network

  web_green:
    container_name: web_green
    image: zerobird/hidden-piece
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=green
    ports:
      - '8082:8081'
    networks:
      - app_network

networks:
  app_network:
    external: true
    internal: true