name: Project CI/CD
on:
  push:
    branches: [ "main", "cicd_test" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: "temurin"

      - name: make application-database.yml
        run: |
          cd ./src/main/resources
          touch .application-database.yml
          echo "${{ secrets.DATABASE }}" >> ./application-database.yml
        shell: bash

      - name: grant execute permission for gradlew
        run: |
          chmod +x gradlew

      - name: project build
        run: |
          ./gradlew build

      - name: build docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hidden-piece . # zerobird

      - name: login docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: push docker hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/hidden-piece # zerobird

      - name: run app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WAS_HOST }}
          username: ${{ secrets.WAS_USERNAME }} # ubuntu
          key: ${{ secrets.WAS_KEY }} # pem key
          script: |
            docker stop $(docker ps -qa) 
            docker rm -f $(docker ps -qa) 
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/hidden-piece
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/hidden-piece-nginx
            sudo chmod 666 /var/run/docker.sock
            sudo chown root:docker /var/run/docker.sock
            docker-compose up -d
            docker image prune -f
#            docker run -d -p 8080:8080 --name test ${{ secrets.DOCKERHUB_USERNAME }}/hidden-piece
